import type { RegisterState } from "./types";

const initialRegisterState: RegisterState = {
  activeStep: 0,
  addressLine: "",
  checkEmailWorker: null,
  checkUsernameWorker: null,
  city: "",
  confirmPassword: "",
  country: "Canada",
  department: "Accounting",
  email: "",
  errorMessage: "",
  filesInError: new Map(),
  firstName: "",
  formData: new FormData(),
  inputsInError: new Set(),
  isEmailExists: false,
  isEmailExistsSubmitting: false,
  isError: false,
  isSubmitting: false,
  isSuccessful: false,
  isUsernameExists: false,
  isUsernameExistsSubmitting: false,
  jobPosition: "Accounting Manager",
  lastName: "",
  password: "",
  postalCodeCanada: "O1O 1O1",
  postalCodeUS: "12345",
  profilePictureUrl: "",
  province: "Alberta",
  registerWorker: null,
  state: "Alabama",
  stepsInError: new Set(),
  stepsWithEmptyInputs: new Set(),
  storeLocation: "All Locations",
  username: "",
};

export { initialRegisterState };
